// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAg1GQCX5RZMloszsa7Y4tF3v74ChiNIE',
    appId: '1:127691217793:web:81cc92b06a31e05de92680',
    messagingSenderId: '127691217793',
    projectId: 'raylytics-2f958',
    authDomain: 'raylytics-2f958.firebaseapp.com',
    storageBucket: 'raylytics-2f958.firebasestorage.app',
    measurementId: 'G-67ZTQSFDNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxpbyxfeLyYxMDv9zwaBMaNrtDTgugbDA',
    appId: '1:127691217793:android:94a7a560d5b44dbee92680',
    messagingSenderId: '127691217793',
    projectId: 'raylytics-2f958',
    storageBucket: 'raylytics-2f958.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA40mxC0RGhWoMuESojC5sTUkA2xSuF0U',
    appId: '1:127691217793:ios:03f198b3e1ee623de92680',
    messagingSenderId: '127691217793',
    projectId: 'raylytics-2f958',
    storageBucket: 'raylytics-2f958.firebasestorage.app',
    iosBundleId: 'com.example.raylytics',
  );
}
